name: queue_up
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  window_manager: ^0.5.1
  tray_manager: ^0.5.2
  bitsdojo_window: ^0.1.6
  shared_preferences: ^2.5.3
  desktop_multi_window: ^0.3.0
  provider: ^6.1.5+1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
